### ISSUE TITLE
Can't convert mutable to immutable type in function call

### ISSUE THREAD

**Issue by DasLixou** [Backseating-Committee-2k/Seatbelt#115] opened 2022-09-08 15:04 UTC
```
function main() {
    let a: mutable = 1;
    let b: const = a;
    illegalshit(@a);
    return;
}

function illegalshit(numba: ->const U32) {
    let c = numba!;
}
```

here the conversion from a (mutable) to b (immutable) is working, but calling illegalshit gets me this error:

```
no matching function overload found with signature "illegalshit(->mutable U32)"
    illegalshit(@a);
    ^~~~~~~~~~~ error occurred here
```

**Comment by mgerhold** [comment] 2022-09-08 15:16
duplicate of #97

**Closed as completed by mgerhold** 2022-09-08 15:16 UTC
